# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sendUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(600, 708)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/MineWechat.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.groupBox_login = QtWidgets.QGroupBox(Form)
        self.groupBox_login.setGeometry(QtCore.QRect(20, 530, 561, 161))
        self.groupBox_login.setObjectName("groupBox_login")
        self.pushButton_logout = QtWidgets.QPushButton(self.groupBox_login)
        self.pushButton_logout.setGeometry(QtCore.QRect(300, 31, 241, 23))
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.pushButton_login = QtWidgets.QPushButton(self.groupBox_login)
        self.pushButton_login.setGeometry(QtCore.QRect(20, 31, 241, 23))
        self.pushButton_login.setObjectName("pushButton_login")
        self.textEdit_output = QtWidgets.QTextEdit(self.groupBox_login)
        self.textEdit_output.setGeometry(QtCore.QRect(21, 70, 521, 74))
        self.textEdit_output.setObjectName("textEdit_output")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(19, 19, 561, 491))
        self.tabWidget.setObjectName("tabWidget")
        self.chat_friend = QtWidgets.QWidget()
        self.chat_friend.setObjectName("chat_friend")
        self.groupBox_friend_record = QtWidgets.QGroupBox(self.chat_friend)
        self.groupBox_friend_record.setGeometry(QtCore.QRect(20, 20, 511, 221))
        self.groupBox_friend_record.setObjectName("groupBox_friend_record")
        self.textEdit_friend_record = QtWidgets.QTextEdit(self.groupBox_friend_record)
        self.textEdit_friend_record.setGeometry(QtCore.QRect(20, 20, 471, 180))
        self.textEdit_friend_record.setObjectName("textEdit_friend_record")
        self.groupBox_text_friend = QtWidgets.QGroupBox(self.chat_friend)
        self.groupBox_text_friend.setGeometry(QtCore.QRect(20, 250, 511, 201))
        self.groupBox_text_friend.setObjectName("groupBox_text_friend")
        self.textEdit_text_friend = QtWidgets.QTextEdit(self.groupBox_text_friend)
        self.textEdit_text_friend.setGeometry(QtCore.QRect(20, 20, 471, 81))
        self.textEdit_text_friend.setObjectName("textEdit_text_friend")
        self.label_text_helper = QtWidgets.QLabel(self.groupBox_text_friend)
        self.label_text_helper.setGeometry(QtCore.QRect(22, 121, 60, 16))
        self.label_text_helper.setObjectName("label_text_helper")
        self.pushButton_text_friend = QtWidgets.QPushButton(self.groupBox_text_friend)
        self.pushButton_text_friend.setGeometry(QtCore.QRect(280, 154, 211, 23))
        self.pushButton_text_friend.setObjectName("pushButton_text_friend")
        self.lineEdit_text_friend = QtWidgets.QLineEdit(self.groupBox_text_friend)
        self.lineEdit_text_friend.setGeometry(QtCore.QRect(80, 155, 171, 20))
        self.lineEdit_text_friend.setObjectName("lineEdit_text_friend")
        self.pushButton_text_helper = QtWidgets.QPushButton(self.groupBox_text_friend)
        self.pushButton_text_helper.setGeometry(QtCore.QRect(80, 121, 411, 23))
        self.pushButton_text_helper.setObjectName("pushButton_text_helper")
        self.label_text_friend = QtWidgets.QLabel(self.groupBox_text_friend)
        self.label_text_friend.setGeometry(QtCore.QRect(22, 155, 60, 16))
        self.label_text_friend.setObjectName("label_text_friend")
        self.tabWidget.addTab(self.chat_friend, "")
        self.chat_chatroom = QtWidgets.QWidget()
        self.chat_chatroom.setObjectName("chat_chatroom")
        self.groupBox_text_chatroom = QtWidgets.QGroupBox(self.chat_chatroom)
        self.groupBox_text_chatroom.setGeometry(QtCore.QRect(20, 250, 511, 201))
        self.groupBox_text_chatroom.setObjectName("groupBox_text_chatroom")
        self.textEdit_text_chatroom = QtWidgets.QTextEdit(self.groupBox_text_chatroom)
        self.textEdit_text_chatroom.setGeometry(QtCore.QRect(20, 20, 471, 81))
        self.textEdit_text_chatroom.setObjectName("textEdit_text_chatroom")
        self.pushButton_text_chatroom = QtWidgets.QPushButton(self.groupBox_text_chatroom)
        self.pushButton_text_chatroom.setGeometry(QtCore.QRect(280, 121, 211, 23))
        self.pushButton_text_chatroom.setObjectName("pushButton_text_chatroom")
        self.lineEdit_text_chatroom = QtWidgets.QLineEdit(self.groupBox_text_chatroom)
        self.lineEdit_text_chatroom.setGeometry(QtCore.QRect(88, 121, 171, 20))
        self.lineEdit_text_chatroom.setObjectName("lineEdit_text_chatroom")
        self.label_text_chatroom = QtWidgets.QLabel(self.groupBox_text_chatroom)
        self.label_text_chatroom.setGeometry(QtCore.QRect(22, 121, 60, 16))
        self.label_text_chatroom.setObjectName("label_text_chatroom")
        self.groupBox_chatroom_record = QtWidgets.QGroupBox(self.chat_chatroom)
        self.groupBox_chatroom_record.setGeometry(QtCore.QRect(20, 20, 511, 221))
        self.groupBox_chatroom_record.setObjectName("groupBox_chatroom_record")
        self.textEdit_chatroom_record = QtWidgets.QTextEdit(self.groupBox_chatroom_record)
        self.textEdit_chatroom_record.setGeometry(QtCore.QRect(20, 20, 471, 180))
        self.textEdit_chatroom_record.setObjectName("textEdit_chatroom_record")
        self.tabWidget.addTab(self.chat_chatroom, "")
        self.file_send = QtWidgets.QWidget()
        self.file_send.setObjectName("file_send")
        self.groupBox_file_dir = QtWidgets.QGroupBox(self.file_send)
        self.groupBox_file_dir.setGeometry(QtCore.QRect(20, 20, 511, 101))
        self.groupBox_file_dir.setObjectName("groupBox_file_dir")
        self.lineEdit_file_dir = QtWidgets.QLineEdit(self.groupBox_file_dir)
        self.lineEdit_file_dir.setGeometry(QtCore.QRect(87, 60, 403, 20))
        self.lineEdit_file_dir.setObjectName("lineEdit_file_dir")
        self.label_file_dir = QtWidgets.QLabel(self.groupBox_file_dir)
        self.label_file_dir.setGeometry(QtCore.QRect(21, 60, 60, 16))
        self.label_file_dir.setObjectName("label_file_dir")
        self.pushButton_open_file = QtWidgets.QPushButton(self.groupBox_file_dir)
        self.pushButton_open_file.setGeometry(QtCore.QRect(21, 30, 471, 23))
        self.pushButton_open_file.setObjectName("pushButton_open_file")
        self.groupBox_file_send = QtWidgets.QGroupBox(self.file_send)
        self.groupBox_file_send.setGeometry(QtCore.QRect(20, 150, 511, 131))
        self.groupBox_file_send.setObjectName("groupBox_file_send")
        self.label_file_helper = QtWidgets.QLabel(self.groupBox_file_send)
        self.label_file_helper.setGeometry(QtCore.QRect(27, 31, 60, 16))
        self.label_file_helper.setObjectName("label_file_helper")
        self.lineEdit_file_chatroom = QtWidgets.QLineEdit(self.groupBox_file_send)
        self.lineEdit_file_chatroom.setGeometry(QtCore.QRect(93, 91, 181, 20))
        self.lineEdit_file_chatroom.setObjectName("lineEdit_file_chatroom")
        self.label_file_friend = QtWidgets.QLabel(self.groupBox_file_send)
        self.label_file_friend.setGeometry(QtCore.QRect(27, 61, 60, 16))
        self.label_file_friend.setObjectName("label_file_friend")
        self.lineEdit_file_friend = QtWidgets.QLineEdit(self.groupBox_file_send)
        self.lineEdit_file_friend.setGeometry(QtCore.QRect(93, 61, 181, 20))
        self.lineEdit_file_friend.setObjectName("lineEdit_file_friend")
        self.pushButton_file_friend = QtWidgets.QPushButton(self.groupBox_file_send)
        self.pushButton_file_friend.setGeometry(QtCore.QRect(290, 60, 201, 23))
        self.pushButton_file_friend.setObjectName("pushButton_file_friend")
        self.label_file_chatroom = QtWidgets.QLabel(self.groupBox_file_send)
        self.label_file_chatroom.setGeometry(QtCore.QRect(27, 91, 60, 16))
        self.label_file_chatroom.setObjectName("label_file_chatroom")
        self.pushButton_file_chatroom = QtWidgets.QPushButton(self.groupBox_file_send)
        self.pushButton_file_chatroom.setGeometry(QtCore.QRect(290, 90, 201, 23))
        self.pushButton_file_chatroom.setObjectName("pushButton_file_chatroom")
        self.pushButton_file_helper = QtWidgets.QPushButton(self.groupBox_file_send)
        self.pushButton_file_helper.setGeometry(QtCore.QRect(93, 30, 399, 23))
        self.pushButton_file_helper.setObjectName("pushButton_file_helper")
        self.tabWidget.addTab(self.file_send, "")
        self.remote = QtWidgets.QWidget()
        self.remote.setObjectName("remote")
        self.groupBox_remote = QtWidgets.QGroupBox(self.remote)
        self.groupBox_remote.setGeometry(QtCore.QRect(20, 20, 511, 421))
        self.groupBox_remote.setObjectName("groupBox_remote")
        self.checkBox_remote = QtWidgets.QCheckBox(self.groupBox_remote)
        self.checkBox_remote.setGeometry(QtCore.QRect(30, 20, 441, 16))
        self.checkBox_remote.setObjectName("checkBox_remote")
        self.textEdit_remote = QtWidgets.QTextEdit(self.groupBox_remote)
        self.textEdit_remote.setGeometry(QtCore.QRect(20, 50, 471, 351))
        self.textEdit_remote.setObjectName("textEdit_remote")
        self.tabWidget.addTab(self.remote, "")
        self.option = QtWidgets.QWidget()
        self.option.setObjectName("option")
        self.groupBox_option = QtWidgets.QGroupBox(self.option)
        self.groupBox_option.setGeometry(QtCore.QRect(20, 10, 511, 421))
        self.groupBox_option.setObjectName("groupBox_option")
        self.checkBox_busy = QtWidgets.QCheckBox(self.groupBox_option)
        self.checkBox_busy.setGeometry(QtCore.QRect(30, 30, 71, 16))
        self.checkBox_busy.setObjectName("checkBox_busy")
        self.checkBox_bot = QtWidgets.QCheckBox(self.groupBox_option)
        self.checkBox_bot.setGeometry(QtCore.QRect(30, 90, 91, 16))
        self.checkBox_bot.setObjectName("checkBox_bot")
        self.lineEdit_busy = QtWidgets.QLineEdit(self.groupBox_option)
        self.lineEdit_busy.setGeometry(QtCore.QRect(110, 50, 381, 20))
        self.lineEdit_busy.setObjectName("lineEdit_busy")
        self.label_busy = QtWidgets.QLabel(self.groupBox_option)
        self.label_busy.setGeometry(QtCore.QRect(30, 50, 81, 20))
        self.label_busy.setObjectName("label_busy")
        self.tabWidget.addTab(self.option, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MineWechat"))
        self.groupBox_login.setTitle(_translate("Form", "系统"))
        self.pushButton_logout.setText(_translate("Form", "注销微信"))
        self.pushButton_login.setText(_translate("Form", "扫码登录"))
        self.groupBox_friend_record.setTitle(_translate("Form", "私聊记录"))
        self.groupBox_text_friend.setTitle(_translate("Form", "发送文字"))
        self.label_text_helper.setText(_translate("Form", "文件助手："))
        self.pushButton_text_friend.setText(_translate("Form", "发给好友"))
        self.pushButton_text_helper.setText(_translate("Form", "发送至文件传输助手"))
        self.label_text_friend.setText(_translate("Form", "好友昵称："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chat_friend), _translate("Form", "微信私聊"))
        self.groupBox_text_chatroom.setTitle(_translate("Form", "发送文字"))
        self.pushButton_text_chatroom.setText(_translate("Form", "发至群聊"))
        self.label_text_chatroom.setText(_translate("Form", "群聊名称："))
        self.groupBox_chatroom_record.setTitle(_translate("Form", "群聊@记录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chat_chatroom), _translate("Form", "微信群聊"))
        self.groupBox_file_dir.setTitle(_translate("Form", "选取文件"))
        self.label_file_dir.setText(_translate("Form", "文件目录："))
        self.pushButton_open_file.setText(_translate("Form", "点击选择文件（暂不支持中文文件名）"))
        self.groupBox_file_send.setTitle(_translate("Form", "发送文件"))
        self.label_file_helper.setText(_translate("Form", "文件助手："))
        self.label_file_friend.setText(_translate("Form", "好友昵称："))
        self.pushButton_file_friend.setText(_translate("Form", "发给好友"))
        self.label_file_chatroom.setText(_translate("Form", "群聊名称："))
        self.pushButton_file_chatroom.setText(_translate("Form", "发至群聊"))
        self.pushButton_file_helper.setText(_translate("Form", "发送至文件传输助手"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.file_send), _translate("Form", "发送文件"))
        self.groupBox_remote.setTitle(_translate("Form", "远程控制"))
        self.checkBox_remote.setText(_translate("Form", "手机端微信控制此电脑"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.remote), _translate("Form", "远程控制"))
        self.groupBox_option.setTitle(_translate("Form", "功能选项"))
        self.checkBox_busy.setText(_translate("Form", "忙碌回复"))
        self.checkBox_bot.setText(_translate("Form", "机器人回复"))
        self.label_busy.setText(_translate("Form", "编辑回复内容："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.option), _translate("Form", "功能选项"))

import img_rc
